=== markwitz/xml_Coding_Da_Vinci/teilnehmerSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:string" name="description"/>
        <xs:element name="members">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="member" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="degree"/>
                    <xs:element type="xs:string" name="university"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== markwitz/xml_Coding_Da_Vinci/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="teilnehmerSchema.xsd">
  <name>XML Coding Da Vinci</name>
  <description>Machen irgendwas</description>
  <members>
    <member>
      <name>Paul Kunze</name>
      <degree>Master Student</degree>
      <university>Freie Universitaet Berlin</university>
    </member>

    <member>
      <name>Dennis Haegler</name>
      <degree>Master Student</degree>
      <university>Freie Universitaet Berlin</university>
    </member>

    <member>
      <name>Lucas Herich</name>
      <degree>Master Student</degree>
      <university>Freie Universitaet Berlin</university>
    </member>

    <member>
      <name>Adrian Zubarev</name>
      <degree>Bachelor Student</degree>
      <university>Freie Universitaet Berlin</university>
    </member>

    <member>
      <name>Christian Biermann</name>
      <degree>Bachelor Student</degree>
      <university>Freie Universitaet Berlin</university>
    </member>

    <member>
      <name>Jan Malte Markwitz</name>
      <degree>Bachelor Student</degree>
      <university>Freie Universitaet Berlin</university>
    </member>
  </members>
</project>
